### PR TITLE
Particles

### PR DESCRIPTION
**Pull request by patriciacarbajal**
@amixofpersons @DakotaMeadows @linkblaine @sgharms

What do you guys think of this layout?
Once you connect, you can click on 'choose mood' and the nav bar pops up. Click 'close' and it goes away.
The track playing is displayed on the bottom of the screen.

### CODE REVIEW

**Comment by amixofpersons** [comment]
@patriciacarbajal Check out your welcome controller and routes. On my end both of these files are behind on what we should have. I'm encountering a strange error where I can't log out because of this.

**Comment by amixofpersons** [comment]
You also have two commented out files and a file with nothing in it in the javascript folder, which is a huge no no. If it's commented out, is it really needed? If not, get rid of it. I'd also fix the indenting on sphere.js because it looks pretty weird.

**Comment by sgharms** [comment]
kisses_from_lana

@amixofpersons - bless you.

**Comment by patriciacarbajal** [comment]
Oh I thought I had gotten rid of those..I was having some git issues getting rid of deleted files.  Thanks I'll fix it

**Comment by amixofpersons** [comment]
@patriciacarbajal Fix the indentation on the particle ring js file and then for some reason there's some extra text in the application.js file. Double check as well we're not requiring any nonexistent js files as well.

**Pull request closed without merging**
